import libisogrid
import importlib
importlib.reload(libisogrid)



# side panel
if False:
    extrudeTris, extrudeSubs = libisogrid.makeGrid(33, \
        71, \
        2, \
        4, \
        [ 1.0, 1.0 ], \
        [ 1.0, 1.0 ], \
        0, \
        0, \
        3, \
        1)
    extrudeTris.Placement = App.Placement(
        App.Vector(8, -35.50, 37.00),
        App.Rotation(App.Vector(0, -1, 0), 270))

# front panel
if True:
    extrudeTris, extrudeSubs = libisogrid.makeGrid(33, \
        47, \
        2, \
        2, \
        [ 1.0, 1.0 ], \
        [ 1.0, 1.0 ], \
        0, \
        0, \
        3, \
        1)
    extrudeTris.Placement = App.Placement(
        App.Vector(-23.50, -20.00, 37.00),
        App.Rotation(App.Vector(.58, .58, -.58), 120))

# top
if False:
    extrudeTris, extrudeSubs = libisogrid.makeGrid(79, \
        55, \
        6, \
        3, \
        [ .5, .5 ], \
        [ .5, .5 ], \
        0, \
        0, \
        3, \
        1)
    extrudeTris.Placement = App.Placement(
        App.Vector(-27.50, 39.50, 17.00),
        App.Rotation(App.Vector(0, 0, 1), 270.00))


# bottom
if False:
    extrudeTris, extrudeSubs = libisogrid.makeGrid(86, \
        62, \
        6, \
        3, \
        [ 1, 1 ], \
        [ 1, 1 ], \
        0, \
        0, \
        4, \
        1)
    extrudeTris.Placement = App.Placement(
        App.Vector(-31, 43, -20.00),
        App.Rotation(App.Vector(0, 0, 1), 270.00))

